name: stats
dependencies:
	- numpy
	- pandas
	- opencv-python
	- cmake
	- dlib
	- face_recognition
	- numpy
	- pandas
	- joblib
	- omegaconf
	- sklearn
	- tensorflow
	- joblib
	- exifread
	- pyvis
	- imutils
	- networkx
	- pytables
	- pillow